"""newt

Revision ID: c65455cc1f29
Revises: 10fbb835b06a
Create Date: 2024-03-27 23:41:36.155112

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c65455cc1f29'
down_revision = '10fbb835b06a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('thread_id', sa.BigInteger(), nullable=True))
    op.create_unique_constraint(op.f('uq_user_thread_id'), 'user', ['thread_id'])
    op.create_unique_constraint(op.f('uq_user_user_id'), 'user', ['user_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_user_user_id'), 'user', type_='unique')
    op.drop_constraint(op.f('uq_user_thread_id'), 'user', type_='unique')
    op.drop_column('user', 'thread_id')
    # ### end Alembic commands ###
